---
- hosts: localhost
  become: no
  tasks:
    - name: "Check ansible version >=2.7.6"
      assert:
        msg: "Ansible must be v2.7.6 or higher"
        that:
          - ansible_version.string is version("2.7.6", ">=")
      tags:
        - check
  vars:
    ansible_connection: local

- hosts: all
  vars:
    ansible_ssh_pipelining: true
  gather_facts: true

- hosts: kube-master
  roles:
    - { role: remove-node/pre-remove, tags: pre-remove }

- hosts: "{{ node | default('kube-node') }}"
  roles:
    - { role: kubespray-defaults }
    - { role: reset, tags: reset }

- hosts: kube-master
  roles:
    - { role: remove-node/post-remove, tags: post-remove }
